### ISSUE TITLE
Population Data differences

### ISSUE THREAD

**Issue by Stephano288** [marcosqlbi/vaccination-italy#3]
Hello,

I noticed that your dashboard brings data about total population for each region / age from Istat.
There is a file, in the open data repository for the vaccinations (platea.csv / platea.json) that includes all the information about age and region that is used also in the offical dashboard from italian government. 
That's why the 2 dashboards includes slightly different numbers when we speak about percentage of the immunization.

Isn't better to have all the data aligned between the 2 dashboards?

Cheers
S.

**Comment by marcosqlbi** [comment]
Thanks for reporting that - that file was (probably) not present when we built the first version of the model and we didn't notice it appeared (or we missed it since the beginning... ).
However, the calculation is now using the platea.csv file, unless there is a filter on Gender, in which case we use the previous data (ISTAT 2020 adjusted for increased age).
It's already published on the public report, too.
Thanks again!

**Comment by marcosqlbi** [comment]
Just one note: the 80+ range doesn't match because we keep 80-89 and 90+ ranges in the existing charts. We use the ISTAT 2020 adjusted info for 80+ ranges.
